// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcs2T2KYc4uFrLMHVeN2IyvFEh9NIc_Y4',
    appId: '1:895361789445:web:dd48cdabc3a7e97aeef66c',
    messagingSenderId: '895361789445',
    projectId: 'flutter-firebase-chat-b842d',
    authDomain: 'flutter-firebase-chat-b842d.firebaseapp.com',
    storageBucket: 'flutter-firebase-chat-b842d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdF8ey8PoJ2fGOhJPeRedEjXeK2lZEX5Q',
    appId: '1:895361789445:android:14683704bbfb3621eef66c',
    messagingSenderId: '895361789445',
    projectId: 'flutter-firebase-chat-b842d',
    storageBucket: 'flutter-firebase-chat-b842d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHybOVs96pZ51UbmxhJklRQbv0T2py08',
    appId: '1:895361789445:ios:d86cc6f7986ef76deef66c',
    messagingSenderId: '895361789445',
    projectId: 'flutter-firebase-chat-b842d',
    storageBucket: 'flutter-firebase-chat-b842d.appspot.com',
    iosClientId: '895361789445-v07a15mgqho38hg67dfakekqvp1je955.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChat',
  );
}
